### ISSUE TITLE
[Question] Calculate loudness of submixer instead of single audio

### ISSUE THREAD

**Issue by ScrappyCocco** [ArthurBarthur/ArthursFancyAudioBPs#1]
Do you think there's an "easy" way to make something as "AudioVizBasicVol" for a submix instead of for a single AudioComponent?

Sometimes it could be useful to know the current loudness of a submix (even if master), but the only way seems to be analyzing the submix frequencies

**Comment by ArthurBarthur** [comment]
Yo! Terrible that I didn't see this earlier:D We can do that, I can put that in V10:) 
The submixes already have an envelope follower, we can take its output and normalize it. If we do this on all submixes in game, and normalize against the loudest or average, we should get relative submix volumes visualized!

**Comment by ArthurBarthur** [comment]
Hey V9.6 is out, it includes simple submix volume meters and more!:)

**Comment by ArthurBarthur** [comment]
yo NOW i notice you wrote "but the only way seems to be analyzing the submix frequencies"

This is the approach in 9.6 as well, but to get that one single final number for volume, we average all the frequencies! 
There is like 50% of an envelope follower system for submixes exposed to BPs, but not enough as far as I can see..

**Comment by ScrappyCocco** [comment]
So the search for the perfect way to do it continue...?

**Comment by ArthurBarthur** [comment]
> So the search for the perfect way to do it continue...?

Well we have the desired end result already, simple submix volume visualizers! But under the hood they are not so different from the freq analysers

**Comment by ArthurBarthur** [comment]
Envelope follower of submix is natively possible in UE(might have been for a while i dunno)! 
These BP nodes https://docs.unrealengine.com/en-US/BlueprintAPI/Audio/EnvelopeFollowing/index.html
